#!/bin/sh
################################################################################
#
# Copyright (C) 2016 Vít Novotný
# License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
# This is free software: you are free to change and redistribute it.
# There is NO WARRANTY, to the extent permitted by law.
#
################################################################################
#
# This script exports an Audacity project $1 to an output file $2. Neither $1
# nor $2 may contain double apostrophes ("); the Audacity mod-script-pipe
# interface provides no (documented) escaping mechanism.
#
################################################################################

{ printf 'OpenProject: Filename="%s" AddToHistory=no\n' "$1";
  printf 'Export: Mode=All Filename="%s" Channels=2\n' "$2"; } |
  audacity-bridge | tail -n1 | grep -q '^Export finished: OK$'
