#!/bin/sh
################################################################################
#
# audacity-bridge - A command-line interface for Audacity
# Copyright (C) 2016 Vít Novotný
# 
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
################################################################################
#
# This script exports an Audacity project $1 to an output file $2. $2 may not
# contain double apostrophes ("); the Audacity mod-script-pipe interface
# provides no (documented) escaping mechanism.
#
################################################################################

printf 'Export: Mode=All Filename="%s" Channels=2\n' "$2" |
audacity-bridge "$1" | tail -n1 | grep -q '^Export finished: OK$'
